// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { useState } from 'react'
import { BrainProvider, useBrain } from '../src/react/BrainProvider'
import { BrainInspector } from '../src/react/components/BrainInspector'
import { BrainAccessibleList } from '../src/renderers/accessible/BrainAccessibleList'
import { BrainContextTray } from '../src/react/components/BrainContextTray'
import type { BrainGraph } from '../src/core/types'
const graph: BrainGraph = { schemaVersion: '1', scopeKey: 's', revision: 'r', completeness: 'complete', nodes: [{ id: 'a', label: 'Alpha', kind: 'unknown-kind', sourceNamespace: 'test', canonicalRef: 'docs:alpha' }, { id: 'b', label: 'Beta', kind: 'document', sourceNamespace: 'test', canonicalRef: 'docs:beta' }], edges: [{ id: 'ab', source: 'a', target: 'b', kind: 'references', directed: true, evidence: { origin: 'synthetic' }, metadata: { explanation: 'Explicit synthetic reference' } }] }
afterEach(cleanup)
function Probe() { const { selectedNodeId, camera } = useBrain(); return <><output data-testid="selection">{selectedNodeId ?? 'none'}</output><button onClick={() => camera.send({ type: 'rotate', yaw: 1, pitch: 0 })}>Rotate</button></> }
describe('composable React integration', () => {
  it('list selection opens the same canonical inspector and handles unknown kinds', () => { render(<BrainProvider graph={graph}><BrainAccessibleList /><BrainInspector renderNodeDetails={node => <p>Custom details for {node.label}</p>} /><Probe /></BrainProvider>); fireEvent.click(screen.getByRole('button', { name: /Alpha unknown-kind/ })); expect(screen.getByTestId('selection').textContent).toBe('a'); expect(screen.getByRole('heading', { name: 'Alpha' })).toBeTruthy(); expect(screen.getByText('Custom details for Alpha')).toBeTruthy(); fireEvent.click(screen.getByRole('tab', { name: /Relationships/ })); fireEvent.click(screen.getByRole('button', { name: /References · directed Beta/ })); expect(screen.getByTestId('selection').textContent).toBe('b') })
  it('implements true controlled selection', () => { const changed = vi.fn(); const { rerender } = render(<BrainProvider graph={graph} selectedNodeId={null} onSelectedNodeChange={changed}><BrainAccessibleList /><Probe /></BrainProvider>); fireEvent.click(screen.getByRole('button', { name: /Alpha unknown-kind/ })); expect(changed).toHaveBeenCalledWith('a'); expect(screen.getByTestId('selection').textContent).toBe('none'); rerender(<BrainProvider graph={graph} selectedNodeId="a" onSelectedNodeChange={changed}><BrainAccessibleList /><Probe /></BrainProvider>); expect(screen.getByTestId('selection').textContent).toBe('a') })
  it('supports a host-controlled state roundtrip', () => { function Host() { const [id, setId] = useState<string | null>(null); return <BrainProvider graph={graph} selectedNodeId={id} onSelectedNodeChange={setId}><BrainAccessibleList /><Probe /></BrainProvider> }; render(<Host />); fireEvent.click(screen.getByRole('button', { name: /Beta document/ })); expect(screen.getByTestId('selection').textContent).toBe('b') })
  it('isolates simultaneous instances and their searches', () => { render(<><section aria-label="Instance one"><BrainProvider graph={graph}><BrainAccessibleList /><Probe /></BrainProvider></section><section aria-label="Instance two"><BrainProvider graph={graph}><BrainAccessibleList /><Probe /></BrainProvider></section></>); const one = within(screen.getByRole('region', { name: 'Instance one' })), two = within(screen.getByRole('region', { name: 'Instance two' })); fireEvent.click(one.getByRole('button', { name: /Alpha unknown-kind/ })); expect(one.getByTestId('selection').textContent).toBe('a'); expect(two.getByTestId('selection').textContent).toBe('none'); fireEvent.change(one.getByRole('textbox'), { target: { value: 'Alpha' } }); expect(two.getByRole('button', { name: /Beta document/ })).toBeTruthy() })
  it('supports a local composition tray but never fabricates unsupported previews', () => { render(<BrainProvider graph={graph} defaultSelectedNodeId="a"><BrainInspector /><BrainContextTray /></BrainProvider>); fireEvent.click(screen.getByRole('button', { name: 'Add to context' })); expect((screen.getByRole('button', { name: 'Preview composition' }) as HTMLButtonElement).disabled).toBe(true); fireEvent.click(screen.getByRole('button', { name: /Context tray/ })); expect(screen.getByText(/Preview unsupported/)).toBeTruthy(); fireEvent.click(screen.getByRole('button', { name: 'Remove Alpha from context' })); expect(screen.getByText(/Add caller-selectable references/)).toBeTruthy() })
  it('escapes unsafe supplied text instead of interpreting markup', () => { const malicious = { ...graph, nodes: [{ ...graph.nodes[0], label: '<script>globalThis.compromised=true</script>' }] , edges: [] }; const { container } = render(<BrainProvider graph={malicious}><BrainAccessibleList /></BrainProvider>); expect(container.querySelector('script')).toBeNull(); expect(container.textContent).toContain('<script>globalThis.compromised=true</script>') })
  it('does not preserve old scoped state when providers receive a different scope', () => { const { rerender } = render(<BrainProvider graph={graph}><BrainAccessibleList /><Probe /></BrainProvider>); fireEvent.click(screen.getByRole('button', { name: /Alpha unknown-kind/ })); rerender(<BrainProvider graph={{ ...graph, scopeKey: 'another-scope', nodes: [], edges: [] }}><BrainAccessibleList /><Probe /></BrainProvider>); expect(screen.getByTestId('selection').textContent).toBe('none'); expect(screen.queryByRole('button', { name: /Alpha unknown-kind/ })).toBeNull() })
})
