import { describe, expect, it } from 'vitest'
import { normalizeForgeCatalog, normalizeForgeGenerationReceipt, normalizeForgeInternalReceipt, normalizeForgeResolveResponse } from '../src/adapters/forge'
import type { ForgeContextReceiptDto, ForgeInternalReceipt } from '../src/adapters/forge'
import { catalogInput, fixtureContext, acmeGraph, summaryGraph, brandRef } from '../../../apps/demo/fixtures/acme'
import { validateGraph } from '../src/core/validation'
const receipt: ForgeContextReceiptDto = { trace_id: 'synthetic', target_model_alias: 'alias', compiled_token_count: null, token_budget_check_deferred: true, sections_dropped: [{ source_ref: brandRef, page_slug: 'voice', version: 'v14', priority: 8, target_tokens: 800 }], compilation_hash: 'b3:synthetic', compiled_at: '2026-10-02T09:00:00Z', context_params_digest: 'synthetic-digest' }
describe('pure Forge projection and receipt adapters', () => {
  it('validates the complete 66-node synthetic fixture', () => { expect(acmeGraph.nodes).toHaveLength(66); expect(validateGraph(acmeGraph)).toEqual([]); expect(acmeGraph.nodes.some(node => node.kind === 'skill')).toBe(true) })
  it('does not invent pages or edges from list summaries', () => { expect(summaryGraph.nodes).toHaveLength(18); expect(summaryGraph.nodes.some(node => node.kind === 'page')).toBe(false); expect(summaryGraph.edges).toHaveLength(0); expect(summaryGraph.completeness).toBe('partial'); expect(summaryGraph.nodes[0].metrics).toMatchObject({ pageCount: 4, loadedPageCount: 0 }) })
  it('preserves supplied list cursors', () => { const graph = normalizeForgeCatalog({ context: fixtureContext, packs: { packs: [], next_cursor: 'synthetic-cursor' } }); expect(graph.nextCursor).toBe('synthetic-cursor') })
  it('manifest total remains unknown if no summary establishes it', () => { const graph = normalizeForgeCatalog({ context: fixtureContext, manifests: catalogInput.manifests?.slice(0, 1) }); expect(graph.nodes.find(node => node.kind === 'pack')?.metrics).toMatchObject({ pageCount: null, loadedPageCount: 4 }) })
  it('does not materialize missing or unauthorized relationship endpoints', () => { const graph = normalizeForgeCatalog({ ...catalogInput, relationships: [{ sourceRef: brandRef, targetRef: 'pack://org/hidden/not-loaded', kind: 'references', directed: true, origin: 'host-supplied', explanation: 'Test' }] }); expect(graph.nodes.some(node => node.label.includes('not-loaded'))).toBe(false) })
  it('public generation preserves aggregates and drops but invents no inclusion/redaction', () => { const observation = normalizeForgeGenerationReceipt(receipt, fixtureContext); expect(observation.status).toBe('success'); if (observation.status !== 'success') throw new Error('Expected receipt'); expect(observation.receipt.compiledTokenCount).toBeNull(); expect(observation.receipt.tokenBudgetCheckDeferred).toBe(true); expect(observation.receipt.contextParamsDigest).toBe('synthetic-digest'); expect(observation.sections).toHaveLength(1); expect(observation.sections[0]).toMatchObject({ outcome: 'dropped', redactionApplied: null, compiledTokenCount: null, pageSlug: 'voice', version: 'v14' }) })
  it('resolve preserves top-level refs/pages without copying compiled content', () => { const observation = normalizeForgeResolveResponse({ resolved_refs: [{ ref: `${brandRef}@v14`, resolved_pages: ['voice'], manifest_etag: 'etag-is-not-version' }], compiled_prompt: { body: 'MUST_NOT_COPY_COMPILED_CONTENT' }, receipt }, fixtureContext); expect(observation.sections.filter(section => section.outcome === 'resolved')).toHaveLength(2); expect(observation.sections.every(section => section.redactionApplied === null)).toBe(true); expect(JSON.stringify(observation)).not.toContain('MUST_NOT_COPY'); expect(JSON.stringify(observation)).not.toContain('etag-is-not-version') })
  it('does not infer actual versions from manifest etags', () => { const observation = normalizeForgeResolveResponse({ resolved_refs: [{ ref: brandRef, manifest_etag: 'v14' }], compiled_prompt: null, receipt }, fixtureContext); expect(observation.sections[0].version).toBeNull() })
  it('only internal receipts provide kept per-section redaction and token evidence', () => { const internal: ForgeInternalReceipt = { ...receipt, tenant_id: 'tenant_demo', resolved_refs: [{ source_ref: brandRef, kind: 'custom-section-kind', version: 'v14', page_slug: 'voice', body_hash: 'synthetic-hash', target_tokens: 800, compiled_token_count: null, redaction_applied: true, redactor_engine: 'unknown-custom-engine' }], redaction_applied: true, redactor_engines: ['unknown-custom-engine'], total_target_tokens: 800 }; const observation = normalizeForgeInternalReceipt(internal, fixtureContext); expect(observation.sections).toHaveLength(2); expect(observation.sections[0]).toMatchObject({ outcome: 'included', redactionApplied: true, compiledTokenCount: null, redactorEngine: 'unknown-custom-engine', pageSlug: 'voice' }); expect(observation.sections[1].outcome).toBe('dropped'); expect(normalizeForgeInternalReceipt({ ...internal, tenant_id: 'different-scope' }, fixtureContext).status).toBe('failure') })
  it('adds observations, never dependency edges or graph mutation', () => { const before = JSON.stringify(acmeGraph); normalizeForgeGenerationReceipt(receipt, fixtureContext); expect(JSON.stringify(acmeGraph)).toBe(before) })
})
