import { expect, test } from '@playwright/test'
const ready = async (page: import('@playwright/test').Page) => { await page.goto('/'); await expect(page.locator('.brain-explorer')).toHaveAttribute('data-ready', 'true') }
test('search, selection, relationship navigation and renderer switches share identities', async ({ page }) => {
  await ready(page)
  await page.getByRole('textbox', { name: 'Search loaded context', exact: true }).fill('review composer')
  await page.getByRole('button', { name: /Review composer skill/ }).click()
  await expect(page.getByRole('heading', { name: 'Review composer' })).toBeVisible()
  await page.getByRole('tab', { name: /Relationships/ }).click()
  await page.getByRole('button', { name: /Declares context · directed Brand voice/ }).click()
  await expect(page.locator('.brain-focused-edge')).toContainText('Review composer → Brand voice')
  await page.getByLabel('Renderer', { exact: true }).selectOption('svg')
  await expect(page.locator('.brain-viewport')).toHaveAttribute('data-active-renderer', 'svg')
  await expect(page.getByRole('heading', { name: 'Brand voice', exact: true })).toBeVisible()
  await page.getByLabel('Renderer', { exact: true }).selectOption('list')
  await expect(page.locator('.brain-viewport')).toHaveAttribute('data-active-renderer', 'list')
  await page.getByRole('button', { name: /^Voice & tone Page/ }).click()
  await expect(page.getByRole('heading', { name: 'Voice & tone' })).toBeVisible()
})
test('drag threshold, discrete rotation, fit, reset and blank-space clearing', async ({ page }) => {
  await ready(page)
  await page.getByLabel('Renderer', { exact: true }).selectOption('svg')
  const before = await page.locator('.brain-svg-renderer > g').getAttribute('transform')
  await page.getByRole('button', { name: 'Rotate left', exact: true }).click()
  await expect(page.locator('.brain-svg-renderer > g')).not.toHaveAttribute('transform', before!)
  const selected = page.locator('.brain-svg-node').filter({ has: page.locator('text', { hasText: /^Brand voice$/ }) })
  const bounds = await selected.boundingBox()
  expect(bounds).toBeTruthy()
  await page.mouse.move(bounds!.x + bounds!.width / 2, bounds!.y + bounds!.height / 2)
  await page.mouse.down(); await page.mouse.move(bounds!.x + 85, bounds!.y + 70, { steps: 8 }); await page.mouse.up()
  await expect(page.getByRole('heading', { name: 'Brand voice', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Fit visible context' }).click()
  await page.getByRole('button', { name: 'Reset camera' }).click()
  await page.locator('.brain-svg-renderer').click({ position: { x: 25, y: 125 } })
  await expect(page.getByRole('complementary', { name: 'Node inspector' })).toHaveCount(0)
})
test('collapse, expand, local composition and receipt uncertainty', async ({ page }) => {
  await ready(page)
  await page.getByRole('button', { name: 'Collapse Organization', exact: true }).click()
  await expect(page.locator('.brain-canvas-caption')).not.toContainText('66 visible nodes')
  await page.getByRole('button', { name: 'Expand Organization', exact: true }).click()
  await expect(page.locator('.brain-canvas-caption')).toContainText('66 visible nodes')
  await page.getByRole('button', { name: 'Add to context', exact: true }).click()
  await page.getByRole('button', { name: 'Preview composition', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Resolution observation' })).toContainText('Simulated')
  await page.getByLabel('Synthetic scenario', { exact: true }).selectOption('generation')
  await expect(page.locator('.brain-receipt-stats')).toContainText('Unknown')
  await expect(page.locator('.brain-receipt-stats')).toContainText('Deferred')
  await page.getByLabel('Synthetic scenario', { exact: true }).selectOption('historical')
  await expect(page.locator('.brain-outcomes')).toContainText('Unmatched: snapshot-mismatch')
  await page.getByLabel('Synthetic scenario', { exact: true }).selectOption('denied')
  await expect(page.locator('.brain-resolution-content')).toContainText('Resolution failed')
})
test('real WebGL canvas rotates and preserves selection across layouts', async ({ page }) => {
  await ready(page)
  await expect(page.locator('.brain-viewport')).toHaveAttribute('data-active-renderer', 'webgl')
  const label = page.locator('.brain-world-label.is-selected')
  const before = await label.getAttribute('style')
  await page.getByRole('button', { name: 'Rotate right', exact: true }).click()
  await expect(label).not.toHaveAttribute('style', before!)
  await page.getByRole('button', { name: 'Graph view', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Brand voice', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Auto-rotate', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Auto-rotate', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Auto-rotate', exact: true })).toHaveAttribute('aria-pressed', 'false')
})
test('navigation and typing pause auto-rotation until explicitly resumed', async ({ page }) => {
  await ready(page)
  const toggle = page.getByRole('button', { name: 'Auto-rotate', exact: true })
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Hide context navigator', exact: true }).click()
  await expect(toggle).toHaveAttribute('aria-pressed', 'false')
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('textbox', { name: 'Search loaded context', exact: true }).focus()
  await page.keyboard.press('r')
  await expect(toggle).toHaveAttribute('aria-pressed', 'false')
  await page.keyboard.press('Escape')
  await expect(toggle).toHaveAttribute('aria-pressed', 'false')
})
test('local graph mutations retain selection and report removed entities', async ({ page }) => {
  await ready(page)
  await page.getByRole('button', { name: 'Open developer playground' }).click()
  await page.getByRole('button', { name: 'Add synthetic node', exact: true }).click()
  await page.getByRole('button', { name: 'Back to explorer', exact: true }).click()
  await expect(page.locator('.brain-statusbar')).toContainText('67 nodes')
  await expect(page.getByRole('heading', { name: 'Brand voice', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Open developer playground' }).click()
  await page.getByRole('button', { name: 'Remove selected synthetic node', exact: true }).click()
  await page.getByRole('button', { name: 'Back to explorer', exact: true }).click()
  await expect(page.getByRole('complementary', { name: 'Selected entity unavailable' })).toBeVisible()
})
test('generic 5000-node data starts in LOD and has a fully reachable semantic list', async ({ page }) => {
  await ready(page)
  await page.getByLabel('Dataset', { exact: true }).selectOption('stress5000')
  await expect(page.locator('.brain-statusbar')).toContainText('5,000 nodes')
  await expect(page.locator('.brain-statusbar')).toContainText('Level-of-detail aggregation')
  await page.getByLabel('Renderer', { exact: true }).selectOption('list')
  await page.getByRole('textbox', { name: 'Search loaded context', exact: true }).first().fill('Synthetic document 4999')
  await page.locator('.brain-search-results button').first().click()
  await expect(page.getByRole('heading', { name: 'Synthetic document 4999' })).toBeVisible()
})
