import { expect, test } from '@playwright/test'
test('sidebar preview delegates to the host Brain tab and fills only its center', async ({ page }) => {
  await page.goto('/embed')
  const preview = page.getByRole('region', { name: 'Knowledge overview' })
  await expect(preview.getByRole('button')).toHaveCount(1)
  await preview.getByRole('button', { name: 'Open Brain tab' }).click()
  await expect(page.getByRole('tab', { name: 'Brain', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.locator('.brain-embedded')).toBeVisible()
  await expect(page.locator('.brain-embedded .brain-viewport')).toHaveAttribute('data-active-renderer', 'webgl')
  expect(await page.evaluate(() => document.fullscreenElement === null)).toBe(true)
  const parent = await page.locator('.embed-content').boundingBox()
  const explorer = await page.locator('.brain-embedded').boundingBox()
  expect(Math.abs(parent!.width - explorer!.width)).toBeLessThan(2)
  expect(Math.abs(parent!.height - explorer!.height)).toBeLessThan(2)
  await page.getByRole('textbox', { name: 'Search loaded context', exact: true }).fill('review composer')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Review composer' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add to context', exact: true })).toHaveCount(0)
  await page.getByRole('tab', { name: 'Content', exact: true }).click()
  await expect(page.locator('.brain-embedded')).toHaveCount(0)
})
test('embedded explorer remains usable on mobile, dark theme, and zero-width changes', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/embed')
  await page.getByRole('tab', { name: 'Brain', exact: true }).click()
  await expect(page.locator('.brain-embedded')).toBeVisible()
  await expect(page.locator('.brain-compact')).toHaveCount(0)
  await page.getByRole('button', { name: 'Use dark theme' }).click()
  await expect(page.locator('.brain-embedded')).toHaveAttribute('data-theme', 'dark')
  await page.getByLabel('Renderer', { exact: true }).selectOption('list')
  await expect(page.getByRole('region', { name: 'Loaded context node list' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
