import { expect, test } from '@playwright/test'
test.beforeEach(async ({ page }) => { await page.goto('/'); await expect(page.locator('.brain-explorer')).toHaveAttribute('data-ready', 'true') })
test('forced WebGL failure and layout timeout leave 2D selection usable', async ({ page }) => {
  await page.getByRole('button', { name: 'Open developer playground' }).click()
  await page.getByLabel('Simulate WebGL initialization failure', { exact: true }).check()
  await page.getByLabel('Simulate layout-worker timeout', { exact: true }).check()
  await page.getByRole('button', { name: 'Back to explorer', exact: true }).click()
  await expect(page.locator('.brain-renderer-notice')).toContainText('Renderer downgraded to 2D')
  await expect(page.locator('.demo-footer')).toContainText('deterministic fallback applied')
  await page.getByRole('button', { name: 'Open accessible node list' }).click()
  await page.getByRole('dialog', { name: 'Accessible node list' }).getByRole('button', { name: /^Voice & tone Page/ }).click()
  await page.getByRole('button', { name: 'Close accessible node list' }).click()
  await expect(page.getByRole('heading', { name: 'Voice & tone' })).toBeVisible()
})
test('real context loss downgrades once and explicit retry restores WebGL', async ({ page }) => {
  await expect(page.locator('.brain-viewport')).toHaveAttribute('data-active-renderer', 'webgl')
  await page.locator('canvas').evaluate(canvas => { const context = (canvas as HTMLCanvasElement).getContext('webgl2'); context?.getExtension('WEBGL_lose_context')?.loseContext() })
  await expect(page.locator('.brain-renderer-notice')).toContainText('context-lost')
  await expect(page.locator('.brain-viewport')).toHaveAttribute('data-active-renderer', 'svg')
  await page.getByRole('button', { name: 'Retry 3D', exact: true }).click()
  await expect(page.locator('.brain-viewport')).toHaveAttribute('data-active-renderer', 'webgl')
  await expect(page.getByRole('heading', { name: 'Brand voice', exact: true })).toBeVisible()
})
test('fullscreen API rejection opens an honest overlay and restores focus', async ({ page }) => {
  await page.evaluate(() => { Element.prototype.requestFullscreen = () => Promise.reject(new Error('iframe restriction')) })
  await page.getByRole('button', { name: 'Enter fullscreen', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Expanded explorer overlay, not native fullscreen' })).toBeVisible()
  await page.getByRole('button', { name: 'Exit overlay', exact: true }).click()
  await expect(page.locator('.brain-explorer')).toHaveAttribute('data-fullscreen', 'none')
  await expect(page.getByRole('button', { name: 'Enter fullscreen', exact: true })).toBeFocused()
  expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden')
})
test('compact embed expands without resetting selection or camera', async ({ page }) => {
  await page.getByRole('button', { name: 'Open developer playground' }).click()
  await page.getByLabel('Container size', { exact: true }).selectOption('embed')
  await page.getByRole('button', { name: 'Back to explorer', exact: true }).click()
  const bounds = await page.locator('.brain-explorer').boundingBox()
  expect(bounds?.width).toBe(320); expect(bounds?.height).toBe(240)
  await page.getByRole('button', { name: 'Open explorer', exact: true }).click()
  await expect(page.locator('.brain-explorer')).toHaveAttribute('data-fullscreen', 'overlay')
  await expect(page.getByRole('heading', { name: 'Brand voice', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Exit overlay', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open explorer', exact: true })).toBeVisible()
})
test('zero-size containers recover when visible again', async ({ page }) => {
  await page.getByLabel('Renderer', { exact: true }).selectOption('svg')
  await page.locator('.demo-explorer-container').evaluate(element => { (element as HTMLElement).style.display = 'none' })
  await expect(page.locator('.brain-explorer')).toBeHidden()
  await page.locator('.demo-explorer-container').evaluate(element => { (element as HTMLElement).style.display = '' })
  await expect(page.locator('.brain-svg-renderer')).toBeVisible()
  const finite = await page.locator('.brain-svg-renderer').evaluate(svg => !svg.innerHTML.includes('NaN'))
  expect(finite).toBe(true)
})
