'use client'
import { useEffect, useId, useRef } from 'react'
import { X, Plus, Trash2, RotateCcw, SlidersHorizontal } from 'lucide-react'
import { useBrain } from '../../../packages/brain/src/react'
import type { DiagnosticEvent } from '../../../packages/brain/src/core'
export type DemoSize = 'workspace' | 'embed' | 'panel' | 'wide'
export interface PlaygroundSettings { size: DemoSize; theme: 'dark' | 'light'; metric: string; forceWebGLFailure: boolean; forceWorkerTimeout: boolean; slowDetails: boolean; customKinds: boolean; diagnostics: boolean }
export function DeveloperPlayground({ settings, onChange, onClose, onAdd, onRemove, onReset, events }: { settings: PlaygroundSettings; onChange: (settings: PlaygroundSettings) => void; onClose: () => void; onAdd: () => void; onRemove: () => void; onReset: () => void; events: readonly DiagnosticEvent[] }) {
  const { view, store, selectedNodeId, camera } = useBrain(), id = useId(), dialog = useRef<HTMLDivElement>(null)
  useEffect(() => {
    const previous = document.activeElement instanceof HTMLElement ? document.activeElement : null
    dialog.current?.querySelector<HTMLElement>('button')?.focus()
    const key = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); event.stopPropagation(); onClose() } if (event.key === 'Tab') { const items = [...(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select') ?? [])]; const first = items[0], last = items.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus() } if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus() } } }
    const element = dialog.current; element?.addEventListener('keydown', key)
    return () => { element?.removeEventListener('keydown', key); previous?.focus() }
  }, [onClose])
  const patch = (value: Partial<PlaygroundSettings>) => onChange({ ...settings, ...value })
  return <div className="demo-modal-backdrop" onClick={event => { if (event.target === event.currentTarget) onClose() }}><section className="demo-playground" ref={dialog} role="dialog" aria-modal="true" aria-labelledby={`${id}-title`}><div className="demo-modal-heading"><span><SlidersHorizontal size={18} /><h2 id={`${id}-title`}>Developer playground</h2></span><button className="brain-icon-button" aria-label="Close developer playground" onClick={onClose}><X size={18} /></button></div><div className="demo-playground-scroll">
    <p className="brain-help">The same library, in a different container. All mutations affect synthetic local fixtures only.</p>
    <div className="demo-playground-fields">
      <div className="brain-field"><label htmlFor={`${id}-size`}>Container size</label><select id={`${id}-size`} value={settings.size} onChange={event => patch({ size: event.target.value as DemoSize })}><option value="workspace">Responsive workspace</option><option value="embed">320 × 240 embed</option><option value="panel">640 × 420 panel</option><option value="wide">Wide 16:9 region</option></select></div>
      <div className="brain-field"><label htmlFor={`${id}-renderer`}>Renderer</label><select id={`${id}-renderer`} value={view.renderer} onChange={event => store.setView({ ...view, renderer: event.target.value as typeof view.renderer })}><option value="auto">Automatic, 3D preferred</option><option value="webgl">3D WebGL</option><option value="svg">2D graph</option><option value="list">Accessible list</option></select></div>
      <div className="brain-field"><label htmlFor={`${id}-layout`}>Layout</label><select id={`${id}-layout`} value={view.layout} onChange={event => store.setView({ ...view, layout: event.target.value as typeof view.layout })}><option value="brain">Bilateral brain volume</option><option value="cluster">Conventional clusters</option></select></div>
      <div className="brain-field"><label htmlFor={`${id}-metric`}>Node-size metric</label><select id={`${id}-metric`} value={settings.metric} onChange={event => patch({ metric: event.target.value })}><option value="targetTokens">Target tokens</option><option value="contentBytes">Content bytes</option><option value="loadedDegree">Loaded incident edge count</option></select></div>
      <div className="brain-field"><label htmlFor={`${id}-theme`}>Theme</label><select id={`${id}-theme`} value={settings.theme} onChange={event => patch({ theme: event.target.value as 'dark' | 'light' })}><option value="dark">Deep ink</option><option value="light">Daylight</option></select></div>
      <div className="brain-field"><label htmlFor={`${id}-quality`}>Rendering quality</label><select id={`${id}-quality`} value={view.quality} onChange={event => store.setView({ ...view, quality: event.target.value as 'high' | 'low' })}><option value="high">High · DPR capped at 1.5</option><option value="low">Low · DPR capped at 1</option></select></div>
    </div>
    <fieldset className="demo-playground-checks"><legend>Failure & isolation scenarios</legend>{([
      ['forceWebGLFailure', 'Simulate WebGL initialization failure'], ['forceWorkerTimeout', 'Simulate layout-worker timeout'], ['slowDetails', 'Delay details by 2 seconds'], ['customKinds', 'Register a custom Note kind'], ['diagnostics', 'Enable content-free diagnostics'],
    ] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={settings[key]} onChange={event => patch({ [key]: event.target.checked })} />{label}</label>)}</fieldset>
    <p className="brain-help">To test scope isolation: enable delayed details, select an entity, then switch datasets before the response arrives. Old-scope details are discarded even if cancellation is ignored.</p>
    <div className="demo-playground-actions"><button className="brain-button" onClick={onAdd}><Plus size={16} />Add synthetic node</button><button className="brain-button" disabled={!selectedNodeId} onClick={onRemove}><Trash2 size={16} />Remove selected synthetic node</button><button className="brain-button" onClick={() => { onReset(); camera.send({ type: 'reset' }) }}><RotateCcw size={16} />Reset fixture</button><button className="brain-button" onClick={() => { store.setView({ ...view, renderer: 'webgl' }); const canvas = document.querySelector<HTMLCanvasElement>('.brain-explorer canvas'); const gl = canvas?.getContext('webgl2'); const extension = gl?.getExtension('WEBGL_lose_context'); if (extension) extension.loseContext() }}>Trigger WebGL context loss</button></div>
    {settings.diagnostics && <div className="demo-diagnostics"><h3>Content-free events</h3><p className="brain-help">Categories and numbers only. No IDs, references, bodies, queries, or raw errors.</p>{events.length ? <ul>{events.slice(-8).map((event, i) => <li key={i}><code>{event.category}</code><span>{event.durationMs !== undefined ? `${event.durationMs.toFixed(2)} ms` : ''}{event.nodeCount !== undefined ? ` · ${event.nodeCount} nodes` : ''}{event.value !== undefined ? ` · value ${event.value.toFixed(2)}` : ''}</span></li>)}</ul> : <p className="brain-help">Interact with the renderer to collect bounded events.</p>}</div>}
  </div><div className="demo-modal-footer"><span>In memory only · no remote mutations</span><button className="brain-button brain-button-primary" onClick={onClose}>Back to explorer</button></div></section></div>
}
